name: Publish

on:
  workflow_dispatch:
    inputs:
      libVersion:
        type: string
        required: true
        description: version of build

jobs:
  buildAndDeploy:

    runs-on: ubuntu-latest
    env :
      JITPACK_USERNAME : ${{ secrets.JITPACK_USERNAME }}
      JITPACK_ACCESS_TOKEN : ${{ secrets.JITPACK_ACCESS_TOKEN }}

    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v1-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v1-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build package
        run: ./gradlew clean buildForDeploy --stacktrace

      - name : Deploy
        run: ./gradlew publishReleasePublicationToMavenRepository -PlibVersion=${{ github.event.inputs.libVersion }} --stacktrace

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties